"""Hardware model enum → human-readable name."""

HARDWARE_MODELS = {
    0:  "Unknown",
    1:  "T-LoRa V2",
    2:  "T-LoRa V1",
    3:  "T-LoRa V2.1 (1.6)",
    4:  "T-Beam",
    5:  "Heltec V2.0",
    6:  "T-Beam V0.7",
    7:  "T-Echo",
    8:  "T-LoRa V1 (1.3)",
    9:  "RAK4631",
    10: "Heltec V2.1",
    11: "Heltec V1",
    12: "T-Beam S3 Core",
    13: "RAK11200",
    14: "Nano G1",
    15: "T-LoRa V2.1 (1.8)",
    16: "T-LoRa T3-S3",
    17: "Nano G1 Explorer",
    18: "Nano G2 Ultra",
    19: "LoRa Type",
    20: "WiPhone",
    21: "WIO WM1110",
    22: "RAK2560",
    23: "Heltec HRU-3601",
    24: "Heltec Wireless Bridge",
    25: "Station G1",
    26: "RAK11310",
    27: "SenseLora RP2040",
    28: "SenseLora S3",
    29: "CanaryOne",
    30: "RP2040 LoRa",
    31: "Station G2",
    36: "nRF52 Unknown",
    39: "DIY V1",
    40: "nRF52840 DK",
    43: "Heltec V3",
    44: "Heltec WSL V3",
    47: "Raspberry Pi Pico",
    48: "Heltec Wireless Tracker",
    49: "Heltec Wireless Paper",
    50: "T-Deck",
    51: "T-Watch S3",
    52: "PiComputer S3",
    53: "Heltec HT62",
    54: "eByte ESP32-S3",
    55: "ESP32-S3 Pico",
    58: "Heltec Wireless Tracker V1.0",
    59: "unPhone",
    63: "nRF52 ProMicro DIY",
    64: "RadioMaster 900 Bandit Nano",
    65: "Heltec Capsule Sensor V3",
    66: "Heltec Vision Master T190",
    67: "Heltec Vision Master E213",
    68: "Heltec Vision Master E290",
    69: "Heltec Mesh Node T114",
    70: "SenseCap Indicator",
    71: "Tracker T1000-E",
    72: "RAK3172",
    74: "RadioMaster 900 Bandit",
    79: "Raspberry Pi Pico 2",
    80: "Seeed XIAO S3",
    81: "Seeed XIAO nRF52840",
    82: "Seeed XIAO nRF52840 Sense",
    88: "T3S3 V1",
    95: "Seeed Solar Node",
    102: "T-Deck Pro",
    110: "Heltec V4",
    255: "Private HW",
}


# Protobuf enum string name → human-readable name
# (meshtastic library often returns the string name instead of the int)
HARDWARE_MODELS_BY_NAME = {
    "UNSET":                       "Unknown",
    "TLORA_V2":                    "T-LoRa V2",
    "TLORA_V1":                    "T-LoRa V1",
    "TLORA_V2_1_1P6":              "T-LoRa V2.1 (1.6)",
    "TBEAM":                       "T-Beam",
    "HELTEC_V2_0":                 "Heltec V2.0",
    "TBEAM_V0P7":                  "T-Beam V0.7",
    "T_ECHO":                      "T-Echo",
    "TLORA_V1_1P3":                "T-LoRa V1 (1.3)",
    "RAK4631":                     "RAK4631",
    "HELTEC_V2_1":                 "Heltec V2.1",
    "HELTEC_V1":                   "Heltec V1",
    "TBEAM_S3_CORE":               "T-Beam S3 Core",
    "RAK11200":                    "RAK11200",
    "NANO_G1":                     "Nano G1",
    "TLORA_V2_1_1P8":              "T-LoRa V2.1 (1.8)",
    "TLORA_T3_S3":                 "T-LoRa T3-S3",
    "NANO_G1_EXPLORER":            "Nano G1 Explorer",
    "NANO_G2_ULTRA":               "Nano G2 Ultra",
    "LORA_TYPE":                   "LoRa Type",
    "WIPHONE":                     "WiPhone",
    "WIO_WM1110":                  "WIO WM1110",
    "RAK2560":                     "RAK2560",
    "HELTEC_HRU3601":              "Heltec HRU-3601",
    "HELTEC_WIRELESS_BRIDGE":      "Heltec Wireless Bridge",
    "STATION_G1":                  "Station G1",
    "RAK11310":                    "RAK11310",
    "SENSELORA_RP2040":            "SenseLora RP2040",
    "SENSELORA_S3":                "SenseLora S3",
    "CANARYONE":                   "CanaryOne",
    "RP2040_LORA":                 "RP2040 LoRa",
    "STATION_G2":                  "Station G2",
    "NRF52_UNKNOWN":               "nRF52 Unknown",
    "DIY_V1":                      "DIY V1",
    "NRF52840DK":                  "nRF52840 DK",
    "HELTEC_V3":                   "Heltec V3",
    "HELTEC_WSL_V3":               "Heltec WSL V3",
    "RAK_WIRELESS_RP2040_V1":      "Raspberry Pi Pico",
    "HELTEC_WIRELESS_TRACKER":     "Heltec Wireless Tracker",
    "HELTEC_WIRELESS_PAPER":       "Heltec Wireless Paper",
    "T_DECK":                      "T-Deck",
    "T_WATCH_S3":                  "T-Watch S3",
    "PICOMPUTER_S3":               "PiComputer S3",
    "HELTEC_HT62":                 "Heltec HT62",
    "EBYTE_ESP32_S3":              "eByte ESP32-S3",
    "ESP32_S3_PICO":               "ESP32-S3 Pico",
    "HELTEC_WIRELESS_TRACKER_V1_0": "Heltec Wireless Tracker V1.0",
    "UNPHONE":                     "unPhone",
    "NRF52_PROMICRO_DIY":          "nRF52 ProMicro DIY",
    "RADIOMASTER_900_BANDIT_NANO": "RadioMaster 900 Bandit Nano",
    "HELTEC_CAPSULE_SENSOR_V3":    "Heltec Capsule Sensor V3",
    "HELTEC_VISION_MASTER_T190":   "Heltec Vision Master T190",
    "HELTEC_VISION_MASTER_E213":   "Heltec Vision Master E213",
    "HELTEC_VISION_MASTER_E290":   "Heltec Vision Master E290",
    "HELTEC_MESH_NODE_T114":       "Heltec Mesh Node T114",
    "SENSECAP_INDICATOR":          "SenseCap Indicator",
    "TRACKER_T1000_E":             "Tracker T1000-E",
    "RAK3172":                     "RAK3172",
    "RADIOMASTER_900_BANDIT":      "RadioMaster 900 Bandit",
    "RASPBERRY_PI_PICO2":          "Raspberry Pi Pico 2",
    "SEEED_XIAO_S3":               "Seeed XIAO S3",
    "XIAO_NRF52_KIT":              "Seeed XIAO nRF52840",
    "XIAO_NRF52_SENSE_KIT":        "Seeed XIAO nRF52840 Sense",
    "T3S3_V1_JP":                  "T3S3 V1",
    "SEEED_SOLAR_NODE":            "Seeed Solar Node",
    "TDECK_PRO":                   "T-Deck Pro",
    "HELTEC_V4":                   "Heltec V4",
    "PRIVATE_HW":                  "Private HW",
}


def hw_model_name(val):
    """Convert a HardwareModel integer or protobuf string to a human-readable string."""
    if val is None:
        return None
    # Try integer lookup first
    try:
        return HARDWARE_MODELS.get(int(val), f"HW#{int(val)}")
    except (TypeError, ValueError):
        pass
    # Fall back to string enum name lookup
    s = str(val)
    return HARDWARE_MODELS_BY_NAME.get(s, s)
